# Path file settings for E018 looper

[settings]

lframes = 65536 # 2**16
nframes = 94
n_avg = 1
sleeptime = 3
static_png_name = "rsa01.png"

[paths]

syncfile = ""
logfile = ""
lustrepath = ""
outpath = ""
wwwpath = ""
